/*
This file belongs to: "@CibNumeritos" (Ha Juegos Copyright 2022), Any unauthorized modification or change will be penalized, more information to authorize your copies you can contact me on discord: https://discord.gg/p6a7tqVJxn
Twitter: https://twitter.com/CibNumeritos
*********************************************************************
Este archivo pertenece a: "@CibNumeritos" (Ha Juegos Copyright 2022), Cualquier modificación o cambio no autorizado será sancionado, más información para autorizar tus copias puedes contactar conmigo en discord: https://discord.gg/p6a7tqVJxn
Su Twitter: https://twitter.com/CibNumeritos
*/
import{PlayerInventoryComponentContainer,world}from"mojang-minecraft";function runCommand(command){try{return{error:false,...world.getDimension('overworld').runCommand(command)};}
catch(error){return{error:true};};};world.events.playerJoin.subscribe(({player})=>{player.addTag('{ActivatedTotem?:0}');player.removeTag('{ActivatedTotem?:1}');});function getDimensionId(dimension){let d=dimension.id
switch(d){case"overworld":{return`§aOverworld§7`}break;case"nether":{return`§cNether§7`}break;case"the end":{return`§9The End§7`}break;};};world.events.tick.subscribe(t=>{try{for(const p of world.getPlayers()){switch(true){case runCommand(`clear "${p.nameTag}" cobblestone 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/stone_age_achievement`);}break;case runCommand(`clear "${p.nameTag}" iron_ingot 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/acquire_hadware_achievement`);}break;case runCommand(`clear "${p.nameTag}" iron_pickaxe 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/iron_pick_achievement`);}break;case runCommand(`clear "${p.nameTag}" diamond 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/diamonds_achievement`);}break;case runCommand(`clear "${p.nameTag}" beacon 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/beacon_achievement`);}break;case runCommand(`clear "${p.nameTag}" blaze_rod 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/blazerod_achievement`);}break;case runCommand(`clear "${p.nameTag}" dragon_egg 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/generation_achievement`);}break;case runCommand(`clear "${p.nameTag}" skull 1 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/wither_skull_achievement`);}break;case runCommand(`clear "${p.nameTag}" netherite_hoe 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/hoe_netherite_achievement`);}break;case runCommand(`clear "${p.nameTag}" ha:shulker_shell 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/shulker_achievement`);}break;case runCommand(`clear "${p.nameTag}" undyed_shulker_box 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/shulker_achievement`);}break;case runCommand(`clear "${p.nameTag}" ha:melted_netherite 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/dumb_achievement`);}break;case runCommand(`clear "${p.nameTag}" ha:broken_netherite 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/dumb_achievement`);}break;case runCommand(`clear "${p.nameTag}" enchanted_golden_apple 0 0`).error==false:{runCommand(`execute "${p.nameTag}" ~ ~ ~ function achievements_functions/appleenchanted_achievement`);}break;};};}catch(e){};});
/*
This file belongs to: "@CibNumeritos" (Ha Juegos Copyright 2022), Any unauthorized modification or change will be penalized, more information to authorize your copies you can contact me on discord: https://discord.gg/p6a7tqVJxn
Twitter: https://twitter.com/CibNumeritos
*********************************************************************
Este archivo pertenece a: "@CibNumeritos" (Ha Juegos Copyright 2022), Cualquier modificación o cambio no autorizado será sancionado, más información para autorizar tus copias puedes contactar conmigo en discord: https://discord.gg/p6a7tqVJxn
Su Twitter: https://twitter.com/CibNumeritos
*/